variables:
  SCIMAGE: scalecommerce/xenial:1.17

stages:
  - Puppet 5
#  - push2github

before_script:
  - apt-get update >/dev/null

.job_template: &full_test
  script:
    - ./test/install-$PUPPET_VERSION.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - cp ./test/yaml/module-$MYSQL_VERSION.yaml  ./test/hieradata/module.yaml
    - puppet apply -v test/site.pp
    - supervisorctl update
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_mysql.rb
    - rm ./test/hieradata/module.yaml

16.04:sc_mysql:mysql-5.6:puppet5:
  stage: Puppet 5
  image: $SCIMAGE
  variables:
    MYSQL_VERSION: 'mysql56'
    PUPPET_VERSION: 'puppet5'
  <<: *full_test


16.04:sc_mysql:mysql-5.7:puppet5:
  stage: Puppet 5
  image: $SCIMAGE
  variables:
    MYSQL_VERSION: 'mysql57'
    PUPPET_VERSION: 'puppet5'
  <<: *full_test

#push2github:
#  stage: push2github
#  script:
#    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_mysql.git
