variables:
  SCIMAGE: scalecommerce/xenial:1.17

stages:
  - Puppet 5
  - Puppet 6

16.04:sc_mysql:mysql-5.6:puppet5:
  stage: Puppet 5
  image: $SCIMAGE
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - mv ./test/hiera/module-mysql56.yaml  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - supervisorctl update
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_mysql.rb

16.04:sc_mysql:mysql-5.7:puppet5:
  stage: Puppet 5
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - export PATH=/opt/puppetlabs/bin:$PATH
    - mv ./test/hiera/module-mysql57.yaml  ./test/hiera/module.yaml
    - puppet apply -v test/site.pp
    - inspec exec test/inspec/sc_mysql.rb

